entrypoint: bundle exec rackup --port $PORT
env: flex
runtime: ruby
# This sample incurs costs to run on the App Engine flexible environment. 
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/ruby/configuring-your-app-with-app-yaml
env_variables:
  SECRET_KEY_BASE: 1cab3df49bec38ea77017666dd9f8b78754538dd6a3d52b7efa7621400a942287e9e0f98a9e004ab06bba98eb6ff673ebb05881ca786894572d6b0279ca65e7e
# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10